### ISSUE TITLE
Create new release for generics

### ISSUE THREAD

**Issue by mjmar01** [mxschmitt/golang-combinations#14]
At the moment `go get github.com/mxschmitt/golang-combinations` will install version `v1.1.0`. This version is missing the generic implementations. Currently an update is only possible manually: `go get -u github.com/mxschmitt/golang-combinations@3a0377e8a1e6357ce47ed5f2acefaada5e3c0baa`

Can you create a new release so the go module tool can pick up the new changes?

**Comment by mxschmitt** [comment]
Will do now!
